class ClojureTemplateProcessor
	def self.clojure_autogenerated
<<EOF
;;;;
;;;; Autogenerated by Jack
;;;;
;;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;;; 
EOF  
	end

	# 
	def self.clojure_name(name)
		name = name.strip
		name.gsub /\s*[^A-Za-z0-9\.\-]\s*/, '-'
	end	

end	